#!/bin/sh

mkdir -p /opt/etc/aiway-manager /opt/var/run
/opt/etc/init.d/S99aiway-manager restart

ip_addr=$(ip -f inet addr show dev br0 2>/dev/null | sed -n 's/.*inet \([0-9.]*\)\/.*/\1/p' | head -1)
[ -n "$ip_addr" ] || ip_addr="192.168.1.1"

echo "AIWAY Manager installed: http://$ip_addr:2222/routing"

exit 0
